### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by comet424** [JMiahMan1/Home-Assistant-Smart-Speaker#5]
hi so copy and pasted the code.. and updated the API key

but it wont compile  i get this error now

INFO ESPHome 2025.4.1
INFO Reading configuration /config/esphome/smart-speaker-1.yaml...
INFO Updating https://github.com/gnumpi/esphome_audio@dev-next
INFO Detected timezone 'America/Toronto'
Failed config

light.esp32_rmt_led_strip: [source /config/esphome/smart-speaker-1.yaml:487]
  platform: esp32_rmt_led_strip
  rgb_order: GRB
  pin: GPIO48
  num_leds: 1
  
  This feature is not available for the IDF framework version 5.
  rmt_channel: 0
  chipset: WS2812
  name: Status LED
  id: led
  disabled_by_default: True
  icon: mdi:led-on
  default_transition_length: 0s
  effects:

**Comment by AndreyShpilevoy** [comment]
Didn't tested yet, but was able to build. 
You need to add the following lines
```
    version: 4.4.8
    platform_version: 5.4.0
```
 to
```
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0
```


and also replace
```
      ref: dev-next
```
with
```
      ref: pull/79/head
```
in
```
external_components:
  - source:
      type: git
      url: https://github.com/gnumpi/esphome_audio
      ref: pull/79/head
    components: [adf_pipeline, i2s_audio]
    refresh: 0s	
```

**Comment by AndreyShpilevoy** [comment]
I couldn't make it fully work. Volume control was broken for me, no matter what I tried.
So I changed it a bit in my fork. Please check if you are interested: [fork](https://github.com/AndreyShpilevoy/Home-Assistant-Smart-Speaker)

I will not make a PR from my branch to this one because I have way too many changes in how the LED indication works.
But if @jmiahman thinks that it's good enough, I can create it. No Problem.

**Comment by comet424** [comment]
hi sorry for the delay.. i havent been around and i didnt get an email  saying there was a reply..  have same issues with kiji and other sites not emailing notifications...  and not in junk..

so  what does the PR mean?  

so i just copy and past the fork?  so far  i built the same project you and the other guy made since of the remix..   i didnt add a speaker  but i have 2ndary speaker for audio output..    i use it as a media player  i know i saw somewhere you can make speaker:  for tts  go to the media player... but cant remember    

i wasnt able to get the led to work  for some reason and i had to change the solder joint as i read in article  someone stated  you gotta solder on DI  not hte DO 

ill have to try this later today.. sorry delay..  i had gotten something working  but  the mic cant always work  or least it doesnt detect the audio    and i was hoping it work on the activation word be whatever you want....  and i find it cant detect  like  turn on lights to work right .. i still new with playing with audio stuff i guess with home assistant it isnt perfect like the echo or the alexia  i guess...  i just built this to try it.. but i find voice activation stuff more headache?  is that normal  with home assistant

**Comment by comet424** [comment]
@AndreyShpilevoy 

so  i copy and pasted your code i couldnt compile it  it gives me error for 
```
speaker: 
    channel: mono
    timeout: never
    buffer_duration: 100ms
```
those 3 options..

now i dont have a speaker attached.. but i do use a a esp32 and a dac plugged into a speaker that does my audio 

```
media_player.speaker_1_esphome_i2s_media_player
```

so havent gotten to test your version  its all a headache lol that 

the Code Home Assistant Voice: Preview Edition

i havent looked at it but is that not a fully working for esp devices like i made from the 2 versions of this 3d printed box i made for the voice assistant...  as id like to use custom wake words too not just the hey jarvis one...
